### ISSUE TITLE
crashing when i visit the page

### ISSUE THREAD

**Issue by bkinsey808** [ericwooley/graphql-typeorm-passport-boilerplate#1]
`npm run dev` doesn't produce any errors, but as soon as I hit the page:

```
Error: req.flash() requires sessions
   at Error (native)
   at IncomingMessage._flash [as flash] (/home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/node_modules/connect-flash/lib/flash.js:60:41)
   at loginForm (/home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/src/auth.ts:95:37)
   at Layer.handle [as handle_request] (/home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/node_modules/express/lib/router/layer.js:95:5)
   at /home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/node_modules/express/lib/router/index.js:330:12)
   at next (/home/bkinsey/opt/gh/bkinsey808/graphql-typeorm-passport-boilerplate/node_modules/express/lib/router/index.js:271:10) 
```

**Comment by ericwooley** [comment]
@bkinsey808 Thanks for trying it out, and reporting back. 

I need a few details, 

What version of node? 
Do you have redis installed? I forgot to list it as  a requirement. I think that is your problem. I pushed an update that mentions redis in the readme.

please note that this is very much a WIP, I would not recommend this for use in production without good testing on your own. Hopefully this gets a little more hardened very quickly.

**Comment by ericwooley** [comment]
Let me know if that wasn't the issue and I can reopen this.
